server:
  port: 80

spring:
  mvc:
    servlet:
      load-on-startup: 1
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: ems
    password: ems
  messages:
    basename: i18n.messages


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.fjrxny.ems.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    name: D:/ProgramData/log/ems/ems.log
  level:
    com.fjrxny.ems: debug